//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REG.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REG.Resources.Enum", typeof(Enum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadly.
        /// </summary>
        public static string Difficulty_Deadly {
            get {
                return ResourceManager.GetString("Difficulty_Deadly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Difficulty_Easy {
            get {
                return ResourceManager.GetString("Difficulty_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Difficulty_Hard {
            get {
                return ResourceManager.GetString("Difficulty_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Difficulty_Medium {
            get {
                return ResourceManager.GetString("Difficulty_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aberration.
        /// </summary>
        public static string MonsterType_Aberration {
            get {
                return ResourceManager.GetString("MonsterType_Aberration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast.
        /// </summary>
        public static string MonsterType_Beast {
            get {
                return ResourceManager.GetString("MonsterType_Beast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celestial.
        /// </summary>
        public static string MonsterType_Celestial {
            get {
                return ResourceManager.GetString("MonsterType_Celestial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construct.
        /// </summary>
        public static string MonsterType_Construct {
            get {
                return ResourceManager.GetString("MonsterType_Construct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        public static string MonsterType_Dragon {
            get {
                return ResourceManager.GetString("MonsterType_Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental.
        /// </summary>
        public static string MonsterType_Elemental {
            get {
                return ResourceManager.GetString("MonsterType_Elemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fey.
        /// </summary>
        public static string MonsterType_Fey {
            get {
                return ResourceManager.GetString("MonsterType_Fey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiend.
        /// </summary>
        public static string MonsterType_Fiend {
            get {
                return ResourceManager.GetString("MonsterType_Fiend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giant.
        /// </summary>
        public static string MonsterType_Giant {
            get {
                return ResourceManager.GetString("MonsterType_Giant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanoid.
        /// </summary>
        public static string MonsterType_Humanoid {
            get {
                return ResourceManager.GetString("MonsterType_Humanoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monstrosity.
        /// </summary>
        public static string MonsterType_Monstrosity {
            get {
                return ResourceManager.GetString("MonsterType_Monstrosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooze.
        /// </summary>
        public static string MonsterType_Ooze {
            get {
                return ResourceManager.GetString("MonsterType_Ooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string MonsterType_Plant {
            get {
                return ResourceManager.GetString("MonsterType_Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarm of Tiny beasts.
        /// </summary>
        public static string MonsterType_SwarmOfTinyBeasts {
            get {
                return ResourceManager.GetString("MonsterType_SwarmOfTinyBeasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undead.
        /// </summary>
        public static string MonsterType_Undead {
            get {
                return ResourceManager.GetString("MonsterType_Undead", resourceCulture);
            }
        }
    }
}
