name: Build and run unit tests

env:
  DOTNET_VERSION: '10.x'
  NODE_VERSION: '24.x'
  PROJECT_PATH: src/REG.Angular
  
on:
  push:
    branches-ignore:    
      - 'main'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-webapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal        

  build-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.PROJECT_PATH }}/package-lock.json

      - name: Install Angular Dependencies
        working-directory: ${{ env.PROJECT_PATH }}
        run: npm ci

      - name: Build Angular
        working-directory: ${{ env.PROJECT_PATH }}
        run: npm run build
